/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import funcionalidad.AccesoLogin;
import funcionalidad.OperacionMaterial;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelo.Usuario;

/**
 *
 * @author C_O_L
 */
public class GuiConsultaMaterial extends javax.swing.JFrame {

    /**
     * Creates new form GuiConsultaMaterial
     */
   
    private DefaultTableModel dtm = new DefaultTableModel();
    
    public GuiConsultaMaterial() {
        initComponents();cargarCategoria();
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        dtm.addColumn("idMaterial");
        dtm.addColumn("nombre");
        dtm.addColumn("volumen");
        dtm.addColumn("cantidad");
        dtm.addColumn("ubicación");
        dtm.addColumn("observaciones");
        dtm.addColumn("Categoria");
        dtm.addColumn("subCategoria");

        tblMaterial.setModel(dtm);cargarmaterial();
        
                    setIconImage(new ImageIcon(getClass().getResource("")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("../img/fondos.jpg"));
        ImageIcon icon = new ImageIcon(uno.getImage().getScaledInstance(800, 800, Image.SCALE_DEFAULT));    
        JLabel fondo = new JLabel();
        fondo.setIcon(icon);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0,1500,600);
        fondo.setBackground(Color.black);
        fondo.setOpaque(true);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboSubCategoria = new javax.swing.JComboBox<>();
        cboCategoria1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterial = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        cboCategoria2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        cboSubCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSubCategoriaActionPerformed(evt);
            }
        });

        cboCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCategoria1ActionPerformed(evt);
            }
        });

        tblMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMaterial);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("subCategoria");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Categoria");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        cboCategoria2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Codigo", "Nombre", "Volumen", "Cantidad", "Ubicacion", "Observacion" }));
        cboCategoria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCategoria2ActionPerformed(evt);
            }
        });

        jButton2.setText("Listar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(206, 206, 206)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 74, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  OperacionMaterial op = new OperacionMaterial();

    private void cargarCategoria() {
        cboCategoria1.addItem("Seleccione");
        op.listadoCategoria().forEach(cate -> {
            cboCategoria1.addItem(cate.getNombreCate());
        });
    }
    private void cargarmaterial() {
        cboCategoria1.setSelectedIndex(0);
        cboCategoria2.setSelectedIndex(0);
        txtBuscar.setText(null);
        dtm.setRowCount(0);
        op.listadoMaterial().forEach(m -> {
            dtm.addRow(new Object[]{m.getIdMaterial(),
                m.getNombre(), m.getVolumen(),
                m.getCantidad(), m.getUbicacion(),
                m.getObservaciones(),
                m.getCateSubCate().getCategoria().getNombreCate(),
                m.getCateSubCate().getSubCategoria().getNombSub()
            });
        });
    }

    private void cboCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCategoria1ActionPerformed
      if (cboCategoria1.getSelectedIndex() == 3) {
            cboSubCategoria.removeAllItems();
            cboSubCategoria.addItem("Seleccione");
            cboSubCategoria.setVisible(true);  jLabel1.setVisible(true);
            op.listadoSubCategoria().forEach(subCate -> {
                cboSubCategoria.addItem(subCate.getNombSub());
            });
            cboSubCategoria.setSelectedIndex(0);
        } else {
            cboSubCategoria.removeAllItems();
            cboSubCategoria.setVisible(false);
            jLabel1.setVisible(false);
        }
          dtm.setRowCount(0);
        op.listadoMaterial().forEach(m -> {
            if(m.getCateSubCate().getCategoria().getIdCategoria() == cboCategoria1.getSelectedIndex())
            dtm.addRow(new Object[]{m.getIdMaterial(),
                m.getNombre(), m.getVolumen(),
                m.getCantidad(), m.getUbicacion(),
                m.getObservaciones(),
                m.getCateSubCate().getCategoria().getNombreCate(),
                m.getCateSubCate().getSubCategoria().getNombSub()
            });
        });
    }//GEN-LAST:event_cboCategoria1ActionPerformed

    private void cboCategoria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCategoria2ActionPerformed
  
    }//GEN-LAST:event_cboCategoria2ActionPerformed

    private void cboSubCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSubCategoriaActionPerformed
     dtm.setRowCount(0);
        op.listadoMaterial().forEach(m -> {
            if(m.getCateSubCate().getCategoria().getIdCategoria() == cboCategoria1.getSelectedIndex()
                    && m.getCateSubCate().getSubCategoria().getSubCate() == cboSubCategoria.getSelectedIndex())
            dtm.addRow(new Object[]{m.getIdMaterial(),
                m.getNombre(), m.getVolumen(),
                m.getCantidad(), m.getUbicacion(),
                m.getObservaciones(),
                m.getCateSubCate().getCategoria().getNombreCate(),
                m.getCateSubCate().getSubCategoria().getNombSub()
            });
        });
    }//GEN-LAST:event_cboSubCategoriaActionPerformed

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
      
     if(txtBuscar.getText().trim().length()>0){
           switch(cboCategoria2.getSelectedIndex()){
          case 1:Filtro(0);break;
           case 2:Filtro(1);break;
            case 3:Filtro(2);break;
             case 4:Filtro(3);break;
              case 5:Filtro(4);break;
              case 6:Filtro(5);break;
      }
     }
      
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   filtro.setRowFilter(null);  cargarmaterial();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
   AccesoLogin ca=new AccesoLogin();
        Usuario use=  ca.Acceso(GuiLogin.matricula,GuiLogin.password);
        if(use != null){    this.dispose();
            GuiPrincipal as = new GuiPrincipal();
                if (use.getRol().getNombreRol().equals("ADMINISTRADOR")) {
                   as.jButton2.setEnabled(false);  
                } else {
                    as.jButton1.setEnabled(false);
                    as.jButton3.setEnabled(false);
                }
                as.setLocationRelativeTo(null);
                as.usuario.setText(use.getNombre().toUpperCase()+"--"+ use.getRol().getNombreRol());
                as.setVisible(true);  
        }else {
                JOptionPane.showMessageDialog(null, "Usuario NO AUTORIZADO!", "ERROR", JOptionPane.ERROR_MESSAGE);

            }
    }//GEN-LAST:event_formWindowClosing
	   TableRowSorter<DefaultTableModel> filtro;
	
		void Filtro(int column){
			txtBuscar.addKeyListener(new KeyAdapter() {
			
			@Override
			public void keyReleased( KeyEvent e) {
				filtro.setRowFilter(RowFilter.regexFilter(txtBuscar.getText().trim(),column));
				
			}});
			
			filtro=new TableRowSorter<DefaultTableModel>(dtm);
		tblMaterial.setRowSorter(filtro);
		}
	
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiConsultaMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiConsultaMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiConsultaMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiConsultaMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiConsultaMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboCategoria1;
    private javax.swing.JComboBox<String> cboCategoria2;
    private javax.swing.JComboBox<String> cboSubCategoria;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMaterial;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
