/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import funcionalidad.AccesoLogin;
import funcionalidad.OperacionMaterial;
import java.awt.Color;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import jdk.internal.org.jline.utils.Colors;
import modelo.CateSubCate;
import modelo.Categoria;
import modelo.Material;
import modelo.Usuario;
import modelo.subCategoria;
import sun.awt.image.PixelConverter;
import static vista.GuiLogin.pass;

/**
 *
 * @author C_O_L
 */
public class GuiMantenimiento extends javax.swing.JFrame {

    /**
     * Creates new form GuiMantenimiento
     */
    private DefaultTableModel dtm = new DefaultTableModel();

    public GuiMantenimiento() {
        initComponents();
        cargarCategoria();  
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        cboSubCategoria.setVisible(false);

        dtm.addColumn("idMaterial");
        dtm.addColumn("nombre");
        dtm.addColumn("civeq");
        dtm.addColumn("kimax");
        dtm.addColumn("sinMarca");
        dtm.addColumn("pirex");
        dtm.addColumn("brand");
        dtm.addColumn("schott_duran");
        dtm.addColumn("pkMexico");
        dtm.addColumn("superiekborosilicate");
        dtm.addColumn("glass");
        dtm.addColumn("p_e");
        dtm.addColumn("volumen");
        dtm.addColumn("cantidad");
        dtm.addColumn("ubicación");
        dtm.addColumn("observaciones");
        dtm.addColumn("Categoria");
        dtm.addColumn("subCategoria");

        tblMaterial.setModel(dtm);
        limpiarCajar();
        habilitarCaja(false);
        habilitarBotone(true, false, false, false);
        cargarmaterial();
        
                setIconImage(new ImageIcon(getClass().getResource("")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("../img/fondos.jpg"));
        ImageIcon icon = new ImageIcon(uno.getImage().getScaledInstance(493, 600, WIDTH));    
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0,1500,600);
        fondo.setBackground(Color.black);
        fondo.setOpaque(true);
        jPanel2.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboCategoria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cboSubCategoria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterial = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCiveq = new javax.swing.JTextField();
        txtkimax = new javax.swing.JTextField();
        txtSinMarca = new javax.swing.JTextField();
        txtPirex = new javax.swing.JTextField();
        txtSimax = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtObservacion = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtSchottDuran = new javax.swing.JTextField();
        txtSuperiekBorosilicate = new javax.swing.JTextField();
        txtGlass = new javax.swing.JTextField();
        txtP_E = new javax.swing.JTextField();
        txtVolumen = new javax.swing.JTextField();
        txtUbicacion = new javax.swing.JTextField();
        txtPKmexica = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        cboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCategoriaActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Categoria");

        cboSubCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSubCategoriaActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SubCategoria");

        tblMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMaterialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMaterial);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("IDENTIFICADOR");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NOMBRE");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("KIMAX");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SIN MARCA");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PIREX");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SIMAX");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("BRAND");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("CANTIDAD");

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("OBSERVACIONES");

        txtNombre.setText("                                   ");

        txtCiveq.setText("                                   ");

        txtkimax.setText("                                   ");

        txtSinMarca.setText("                                   ");

        txtPirex.setText("                                   ");

        txtSimax.setText("                                   ");

        txtBrand.setText("                                   ");

        txtCantidad.setText("                                   ");

        txtObservacion.setText("                                   ");
        txtObservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObservacionActionPerformed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("SCHOTT DURAN");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SUPERIEK BOROSILICATE");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("GLASS");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("P.E");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("VOLUMEN");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("UBICACIÓN");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("P.K. MEXICO");

        txtSchottDuran.setText("                                   ");

        txtSuperiekBorosilicate.setText("                  ");

        txtGlass.setText("                ");

        txtP_E.setText("                                   ");

        txtVolumen.setText("                                   ");

        txtPKmexica.setText("                                   ");

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("CIVEP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCiveq, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtkimax, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSinMarca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPirex, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtObservacion)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBrand, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSimax))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtSchottDuran, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel21)
                                .addComponent(jLabel18)
                                .addComponent(jLabel17)
                                .addComponent(jLabel16))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtVolumen)
                                .addComponent(txtUbicacion)
                                .addComponent(txtPKmexica)
                                .addComponent(txtP_E, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGlass, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSuperiekBorosilicate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtGlass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(txtSchottDuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtSuperiekBorosilicate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtP_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPKmexica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCiveq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkimax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSinMarca)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPirex)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSimax)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBrand)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    OperacionMaterial op = new OperacionMaterial();

    private void cargarCategoria() {
        cboCategoria.addItem("Seleccione");
        op.listadoCategoria().forEach(cate -> {
            cboCategoria.addItem(cate.getNombreCate());
        });
         this.getContentPane().setBackground(Color.red);
    }

    public void limpiarCajar() {
        List<Material> lista = op.listadoMaterial();
        txtId.setText((lista.get(lista.size() - 1).getIdMaterial() + 1) + "");
        txtUbicacion.setText(null);
        txtVolumen.setText(null);
        txtCiveq.setText(null);
        txtGlass.setText(null);
        txtObservacion.setText(null);
        txtP_E.setText(null);
        txtSchottDuran.setText(null);
        txtkimax.setText(null);
        txtSuperiekBorosilicate.setText(null);
        txtBrand.setText(null);
        txtSimax.setText(null);
        txtSinMarca.setText(null);
        txtPirex.setText(null);
        txtNombre.setText(null);
        txtCantidad.setText(null);
        cboCategoria.setSelectedIndex(0);
        txtPKmexica.setText(null);

    }

    public void habilitarCaja(boolean b) {
        txtId.setEnabled(false);
        txtNombre.setEnabled(b);
        txtUbicacion.setEnabled(b);
        txtVolumen.setEnabled(b);
        txtCiveq.setEnabled(b);
        txtGlass.setEnabled(b);
        txtObservacion.setEnabled(b);
        txtP_E.setEnabled(b);
        txtSchottDuran.setEnabled(b);
        txtkimax.setEnabled(b);
        txtSuperiekBorosilicate.setEnabled(b);
        cboCategoria.setEnabled(b);
        cboSubCategoria.setEnabled(b);
        txtBrand.setEnabled(b);
        txtSimax.setEnabled(b);
        txtSinMarca.setEnabled(b);
        txtPirex.setEnabled(b);
        txtCantidad.setEnabled(b);
        txtPKmexica.setEnabled(b);

    }

    public void habilitarBotone(boolean n, boolean a, boolean e, boolean ed) {
        btnAgregar.setEnabled(a);
        btnEliminar.setEnabled(e);
        btnNuevo.setEnabled(n);
        btnEditar.setEnabled(ed);
    }
    
    private void cboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCategoriaActionPerformed

        if (String.valueOf(cboCategoria.getSelectedItem()).equalsIgnoreCase("Reactivos")) {

            cboSubCategoria.removeAllItems();
            cboSubCategoria.addItem("Seleccione");
            cboSubCategoria.setVisible(true);
            jLabel3.setVisible(true);
            op.listadoSubCategoria().forEach(subCate -> {
                cboSubCategoria.addItem(subCate.getNombSub());
            });
            cboSubCategoria.setSelectedIndex(0);
        } else {
            cboSubCategoria.removeAllItems();
            cboSubCategoria.setVisible(false);
            jLabel3.setVisible(false);
        }
        if (String.valueOf(cboCategoria.getSelectedItem()).equalsIgnoreCase("Reactivos")
                || String.valueOf(cboCategoria.getSelectedItem()).equalsIgnoreCase("ALMACEN")) {

            txtUbicacion.setEditable(true);
            txtPKmexica.setEditable(false);
            txtVolumen.setEnabled(true);
            txtCiveq.setEditable(false);
            txtGlass.setEditable(false);
            txtObservacion.setEditable(false);
            txtP_E.setEditable(false);
            txtSchottDuran.setEditable(false);
            txtkimax.setEditable(false);
            txtSuperiekBorosilicate.setEditable(false);
            txtBrand.setEditable(false);
            txtSimax.setEditable(false);
            txtSinMarca.setEditable(false);
            txtPirex.setEditable(false);
          
            txtUbicacion.setBackground(new Color(255,255,255));
            txtVolumen.setBackground(new Color(255,255,255));
              txtCantidad.setBackground(new Color(255,255,255));
            txtCiveq.setBackground(new Color(153,153,153));
            txtGlass.setBackground(new Color(153,153,153));
            txtObservacion.setBackground(new Color(153,153,153));
            txtP_E.setBackground(new Color(153,153,153));
            txtSchottDuran.setBackground(new Color(153,153,153));
            txtkimax.setBackground(new Color(153,153,153));
            txtSuperiekBorosilicate.setBackground(new Color(153,153,153));
            txtBrand.setBackground(new Color(153,153,153));
            txtSimax.setBackground(new Color(153,153,153));
            txtSinMarca.setBackground(new Color(153,153,153));
            txtPirex.setBackground(new Color(153,153,153));
            txtPKmexica.setBackground(new Color(153,153,153));
    
        } else if (String.valueOf(cboCategoria.getSelectedItem()).equalsIgnoreCase("Equipos")) {

            txtUbicacion.setEditable(true);
            txtVolumen.setEditable(false);
            txtPKmexica.setEditable(false);

            txtBrand.setEditable(false);
            txtCiveq.setEditable(false);
            txtGlass.setEditable(false);
            txtObservacion.setEditable(false);
            txtP_E.setEditable(false);
            txtSchottDuran.setEditable(false);
            txtkimax.setEditable(false);
            txtSuperiekBorosilicate.setEditable(false);
            txtSimax.setEditable(false);
            txtSinMarca.setEditable(false);
            txtPirex.setEditable(false);
            
            txtUbicacion.setBackground(new Color(255,255,255));
            txtCantidad.setBackground(new Color(255,255,255));
            txtVolumen.setBackground(new Color(255,255,255));
            txtCiveq.setBackground(new Color(153,153,153));
            txtGlass.setBackground(new Color(153,153,153));
            txtObservacion.setBackground(new Color(153,153,153));
            txtP_E.setBackground(new Color(153,153,153));
            txtSchottDuran.setBackground(new Color(153,153,153));
            txtkimax.setBackground(new Color(153,153,153));
            txtSuperiekBorosilicate.setBackground(new Color(153,153,153));
            txtBrand.setBackground(new Color(153,153,153));
            txtSimax.setBackground(new Color(153,153,153));
            txtSinMarca.setBackground(new Color(153,153,153));
            txtPirex.setBackground(new Color(153,153,153));
            txtPKmexica.setBackground(new Color(153,153,153));
        } else {
            txtUbicacion.setEditable(true);
            txtPKmexica.setEditable(true);
            txtBrand.setEditable(true);
            txtCiveq.setEditable(true);
            txtGlass.setEditable(true);
            txtObservacion.setEditable(true);
            txtP_E.setEditable(true);
            txtSchottDuran.setEditable(true);
            txtkimax.setEditable(true);
            txtSuperiekBorosilicate.setEditable(true);
            txtBrand.setEditable(true);
            txtSimax.setEditable(true);
            txtSinMarca.setEditable(true);
            txtPirex.setEditable(true);
            
           txtUbicacion.setBackground(new Color(255,255,255));
            txtVolumen.setBackground(new Color(255,255,255));
           txtCantidad.setBackground(new Color(255,255,255));
            txtCiveq.setBackground(new Color(255,255,255));
            txtGlass.setBackground(new Color(255,255,255));
            txtObservacion.setBackground(new Color(255,255,255));
            txtP_E.setBackground(new Color(255,255,255));
            txtSchottDuran.setBackground(new Color(255,255,255));
            txtkimax.setBackground(new Color(255,255,255));
            txtSuperiekBorosilicate.setBackground(new Color(255,255,255));
            txtBrand.setBackground(new Color(255,255,255));
            txtSimax.setBackground(new Color(255,255,255));
            txtSinMarca.setBackground(new Color(255,255,255));
            txtPirex.setBackground(new Color(255,255,255));
            txtPKmexica.setBackground(new Color(255,255,255));
    
                  
        }
    }//GEN-LAST:event_cboCategoriaActionPerformed

    private void cargarmaterial() {
        dtm.setRowCount(0);
        op.listadoMaterial().forEach(m -> {
            dtm.addRow(new Object[]{m.getIdMaterial(),
                m.getNombre(), m.getCiveq(), m.getKimax(),
                m.getSimax(), m.getPirex(), m.getBrand(), m.getSchott_duran(),
                m.getPkMexico(), m.getSuperiekborosilicate(),
                m.getGlass(), m.getP_e(), m.getVolumen(),
                m.getCantidad(), m.getUbicacion(),
                m.getObservaciones(),
                m.getCateSubCate().getCategoria().getNombreCate(),
                m.getCateSubCate().getSubCategoria().getNombSub()
            });
        });
    }
    
    private void cboSubCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSubCategoriaActionPerformed

    }//GEN-LAST:event_cboSubCategoriaActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiarCajar();
        habilitarCaja(true);
        habilitarBotone(false, true, false, false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

           Material m=obtenerDataMaterial();
        if(m!= null){
                 if (JOptionPane.showConfirmDialog(null, "Desea Agregar?", "confirme",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

            if (op.saveMaterial(m)) {
                JOptionPane.showMessageDialog(null, "Se Agrego correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "Error al Agregar");
            }
            cargarmaterial();
            limpiarCajar();
            habilitarCaja(false);
            habilitarBotone(true, false, false, false);
        }
        }


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Material m=obtenerDataMaterial();
        if(m!= null){
                 if (JOptionPane.showConfirmDialog(null, "Desea Modificar?", "confirme",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

            if (op.saveMaterial(m)) {
                JOptionPane.showMessageDialog(null, "Se Modifico correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "Error al Modificar");
            }
            cargarmaterial();
            limpiarCajar();
            habilitarCaja(false);
            habilitarBotone(true, false, false, false);
        }
        }
   
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        if (tblMaterial.getSelectedRow() >= 0) {
            if (JOptionPane.showConfirmDialog(null, "Eliminar el material?", "Confirmar", JOptionPane.YES_NO_OPTION)
                    == JOptionPane.YES_OPTION) {
                boolean bandera = op.EliminarMaterial(Integer.parseInt(
                        String.valueOf(tblMaterial.getValueAt(tblMaterial.getSelectedRow(), 0))));
                if (bandera) {
                    cargarmaterial();
                    JOptionPane.showMessageDialog(null, "Se elimino correctamente");
                    limpiarCajar();
                    habilitarCaja(false);
                    habilitarBotone(true, false, false, false);
                } else {
                    JOptionPane.showMessageDialog(null, "Error al eliminar");

                }
            } else {

                tblMaterial.setSelectionMode(-1);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un fila");

        }


    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtObservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservacionActionPerformed
    }//GEN-LAST:event_txtObservacionActionPerformed
 
    private Material obtenerDataMaterial() {

        if (cboCategoria.getSelectedIndex() != 0) {
            if (txtNombre.getText().trim().length() > 0) {
                if (txtCantidad.getText().trim().length() > 0) {
                    if (txtUbicacion.getText().trim().length() > 0) {
                        switch (cboCategoria.getSelectedIndex()) {
                            case 1:
                                if (txtCiveq.getText().trim().length() > 0) {
                                    if (txtCiveq.getText().trim().length() > 0) {
                                        if (txtkimax.getText().trim().length() > 0) {
                                            if (txtSinMarca.getText().trim().length() > 0) {
                                                if (txtPirex.getText().trim().length() > 0) {
                                                    if (txtSimax.getText().trim().length() > 0) {
                                                        if (txtBrand.getText().trim().length() > 0) {
                                                            if (txtSchottDuran.getText().trim().length() > 0) {
                                                                if (txtPKmexica.getText().trim().length() > 0) {
                                                                    if (txtSuperiekBorosilicate.getText().trim().length() > 0) {
                                                                        if (txtP_E.getText().trim().length() > 0) {
                                                                            if (txtVolumen.getText().trim().length() > 0) {
                                                                                if (txtObservacion.getText().trim().length() > 0) {
                                                                                    if (txtBrand.getText().trim().length() > 0) {
                                                                                        return new Material(
                                                                                                Integer.parseInt(txtId.getText()), txtNombre.getText().trim(),
                                                                                                txtCiveq.getText().trim(), txtkimax.getText().trim(), txtSinMarca.getText().trim(),
                                                                                                txtPirex.getText().trim(), txtSimax.getText().trim(),
                                                                                                txtBrand.getText().trim(), txtSchottDuran.getText().trim(),
                                                                                                txtPKmexica.getText().trim(), txtSuperiekBorosilicate.getText().trim(),
                                                                                                txtGlass.getText().trim(), txtP_E.getText().trim(), txtVolumen.getText().trim(),
                                                                                                txtCantidad.getText().trim(), txtUbicacion.getText().trim(),
                                                                                                txtObservacion.getText().trim(),
                                                                                                new CateSubCate(op.buscarIdSubCate_and_Categoria(cboCategoria.getSelectedIndex(), 0)));

                                                                                    } else {
                                                                                        JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
                                                                                    }
                                                                                } else {
                                                                                    JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
                                                                                }
                                                                            } else {
                                                                                JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
                                                                            }
                                                                        } else {
                                                                            JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
                                                                        }
                                                                    } else {
                                                                        JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
                                                                    }
                                                                } else {
                                                                    JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
                                                                }
                                                            } else {
                                                                JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
                                                            }
                                                        } else {
                                                            JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
                                                        }
                                                    } else {
                                                        JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
                                                    }
                                                } else {
                                                    JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
                                                }
                                            } else {
                                                JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
                                            }
                                        } else {
                                            JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
                                }

                                break;
                            case 2:
                                return new Material(
                                        Integer.parseInt(txtId.getText()),
                                        txtNombre.getText().trim(),
                                        txtCantidad.getText().trim(),
                                        txtUbicacion.getText().trim(),
                                        new CateSubCate(op.buscarIdSubCate_and_Categoria(cboCategoria.getSelectedIndex(), 0)));

                            case 3:
                                if (txtVolumen.getText().trim().length() > 0) {
                                    if (cboSubCategoria.getSelectedIndex() != 0) {
                                        return new Material(
                                                Integer.parseInt(txtId.getText()),
                                                txtNombre.getText().trim(),
                                                txtVolumen.getText().trim(),
                                                txtCantidad.getText().trim(),
                                                txtUbicacion.getText().trim(),
                                                new CateSubCate(op.buscarIdSubCate_and_Categoria(cboCategoria.getSelectedIndex(), cboSubCategoria.getSelectedIndex())));

                                    } else {
                                        JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
                                }

                            default:
                                if (txtVolumen.getText().trim().length() > 0) {
                                    return new Material(
                                            Integer.parseInt(txtId.getText()),
                                            txtNombre.getText().trim(),
                                            txtVolumen.getText().trim(),
                                            txtCantidad.getText().trim(),
                                            txtUbicacion.getText().trim(),
                                            new CateSubCate(op.buscarIdSubCate_and_Categoria(cboCategoria.getSelectedIndex(), 0)));
                                } else {
                                    JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
                                }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese Todo los campos");
        }
        return null;
    }
   
    private void tblMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMaterialMouseClicked

        int row = tblMaterial.getSelectedRow();
        if (row >= 0) {
            Material m = op.buscarMaterial(Integer.parseInt(String.valueOf(tblMaterial.getValueAt(row, 0))));
            if (m != null) {
                limpiarCajar();
                txtId.setText(m.getIdMaterial() + "");
                txtNombre.setText(m.getNombre());
                txtCantidad.setText(m.getCantidad());
                txtUbicacion.setText(m.getUbicacion());
                txtVolumen.setText(m.getVolumen());
                int cate = m.getCateSubCate().getCategoria().getIdCategoria();
                cboCategoria.setSelectedIndex(cate);
                switch (cate) {
                    case 1:
                        txtCiveq.setText(m.getCiveq());
                        txtkimax.setText(m.getKimax());
                        txtSinMarca.setText(m.getSinMarca());
                        txtPirex.setText(m.getPirex());
                        txtSimax.setText(m.getSimax());
                        txtBrand.setText(m.getBrand());
                        txtSchottDuran.setText(m.getSchott_duran());
                        txtPKmexica.setText(m.getPkMexico());
                        txtSuperiekBorosilicate.setText(m.getSuperiekborosilicate());
                        txtGlass.setText(m.getGlass());
                        txtP_E.setText(m.getP_e());
                        txtObservacion.setText(m.getObservaciones());
                        break;
                    case 3:
                        cboSubCategoria.setSelectedIndex(m.getCateSubCate().getSubCategoria().getSubCate());
                        break;
                }
                habilitarCaja(true);
                habilitarBotone(true, false, true, true);
            }

        }

    }//GEN-LAST:event_tblMaterialMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       AccesoLogin ca=new AccesoLogin();
        Usuario use=  ca.Acceso(GuiLogin.matricula,GuiLogin.password);
        if(use != null){    this.dispose();
            GuiPrincipal as = new GuiPrincipal();
                if (use.getRol().getNombreRol().equals("ADMINISTRADOR")) {
                   as.jButton2.setEnabled(false);  
                } else {
              
                    as.jButton1.setEnabled(false);
                    as.jButton3.setEnabled(false);
                }
                as.setLocationRelativeTo(null);
                as.usuario.setText(use.getNombre().toUpperCase()+"--"+ use.getRol().getNombreRol());
                as.setVisible(true);  
        }else {
                JOptionPane.showMessageDialog(null, "Usuario NO AUTORIZADO!", "ERROR", JOptionPane.ERROR_MESSAGE);

            }
      
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JComboBox<String> cboSubCategoria;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMaterial;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCiveq;
    private javax.swing.JTextField txtGlass;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtObservacion;
    private javax.swing.JTextField txtPKmexica;
    private javax.swing.JTextField txtP_E;
    private javax.swing.JTextField txtPirex;
    private javax.swing.JTextField txtSchottDuran;
    private javax.swing.JTextField txtSimax;
    private javax.swing.JTextField txtSinMarca;
    private javax.swing.JTextField txtSuperiekBorosilicate;
    private javax.swing.JTextField txtUbicacion;
    private javax.swing.JTextField txtVolumen;
    private javax.swing.JTextField txtkimax;
    // End of variables declaration//GEN-END:variables
}
